import type { ExerciseInput, ExerciseMuscle, LoadType, MuscleGroup, SideMode, TrackingType } from "./entities";

type Options = {
  trackingType?: TrackingType;
  defaultLoadType?: LoadType;
  sideMode?: SideMode;
};

const primary = (muscleGroup: MuscleGroup, weight = 1): ExerciseMuscle => ({ muscleGroup, role: "primary", weight });
const secondary = (muscleGroup: MuscleGroup, weight: number): ExerciseMuscle => ({ muscleGroup, role: "secondary", weight });

function exercise(
  name: string,
  equipment: string,
  movementPattern: string,
  instructions: string,
  muscles: ExerciseMuscle[],
  options: Options = {},
): ExerciseInput {
  return {
    name,
    equipment,
    movementPattern,
    instructions,
    muscles,
    trackingType: options.trackingType ?? "reps",
    defaultLoadType: options.defaultLoadType ?? "external",
    sideMode: options.sideMode ?? "bilateral",
  };
}

export const homeGymExercises: ExerciseInput[] = [
  exercise(
    "Wide-grip pull-up",
    "pull_up_station",
    "vertical_pull",
    "Use the wide angled handles. Start from a controlled hang, pull your upper chest toward the bar, and lower without swinging.",
    [primary("back"), secondary("biceps", 0.4), secondary("grip", 0.3)],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Neutral-grip pull-up",
    "pull_up_station",
    "vertical_pull",
    "Use the parallel handles with palms facing each other. Keep ribs down, drive elbows toward your sides, and finish each rep under control.",
    [primary("back"), secondary("biceps", 0.5), secondary("grip", 0.3)],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Chin-up",
    "pull_up_station",
    "vertical_pull",
    "Take a shoulder-width underhand grip. Pull without kicking, keep the shoulders away from the ears, and lower to a controlled hang.",
    [primary("back"), secondary("biceps", 0.7), secondary("grip", 0.3)],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Scapular pull-up",
    "pull_up_station",
    "vertical_pull",
    "Hang with straight elbows. Pull the shoulder blades down to lift the body slightly, pause, then return to the hang without bending the arms.",
    [primary("back"), secondary("grip", 0.25)],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Hanging straight-leg raise",
    "pull_up_station",
    "core",
    "Hang without swinging, brace the trunk, and raise straight legs as high as you can while keeping the movement controlled.",
    [primary("core"), secondary("grip", 0.35)],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Captain's chair knee raise",
    "dip_knee_raise_station",
    "core",
    "Press your back and forearms into the pads. Curl the knees toward the chest without using momentum, then lower slowly.",
    [primary("core")],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Captain's chair straight-leg raise",
    "dip_knee_raise_station",
    "core",
    "Support yourself against the pads, keep the legs long, and raise them under control without arching away from the back pad.",
    [primary("core")],
    { defaultLoadType: "bodyweight" },
  ),

  exercise(
    "Machine chest press",
    "multi_gym",
    "horizontal_push",
    "Set the seat so the handles line up around mid-chest. Keep your upper back against the pad and press without snapping the elbows straight.",
    [primary("chest"), secondary("triceps", 0.6), secondary("shoulders", 0.4)],
  ),
  exercise(
    "Pec deck fly",
    "multi_gym",
    "horizontal_push",
    "Adjust the seat so the upper arms are near chest height. Bring the arms together with a soft elbow bend and return only as far as the shoulders stay comfortable.",
    [primary("chest"), secondary("shoulders", 0.25)],
  ),
  exercise(
    "Straight-arm cable pulldown",
    "high_cable",
    "vertical_pull",
    "Attach the straight bar to the high pulley. Hinge slightly, keep the elbows nearly straight, and pull the bar toward the thighs using the lats.",
    [primary("back"), secondary("triceps", 0.2), secondary("core", 0.2)],
  ),
  exercise(
    "Close-grip lat pulldown",
    "high_cable",
    "vertical_pull",
    "Use the close-grip handle. Keep the torso tall, pull toward the upper chest, and let the shoulder blades rise under control between reps.",
    [primary("back"), secondary("biceps", 0.5), secondary("grip", 0.2)],
  ),
  exercise(
    "Single-arm cable row",
    "low_cable",
    "horizontal_pull",
    "Use a single handle on the low pulley. Keep your torso square and pull the elbow toward the hip without rotating.",
    [primary("back"), secondary("biceps", 0.4), secondary("grip", 0.2)],
    { sideMode: "per_side" },
  ),
  exercise(
    "Cable biceps curl",
    "low_cable",
    "elbow_flexion",
    "Attach the short bar to the low pulley. Keep the upper arms still and curl without leaning back.",
    [primary("biceps"), secondary("grip", 0.2)],
  ),
  exercise(
    "Overhead cable triceps extension",
    "high_cable",
    "elbow_extension",
    "Face away from the high pulley with the attachment behind your head. Keep the elbows pointed forward and extend without arching the back.",
    [primary("triceps"), secondary("core", 0.15)],
  ),
  exercise(
    "Single-arm cable lateral raise",
    "low_cable",
    "shoulder_abduction",
    "Stand side-on to the low pulley. Raise the handle to about shoulder height with a soft elbow and keep the torso still.",
    [primary("shoulders")],
    { sideMode: "per_side" },
  ),
  exercise(
    "Single-arm cable front raise",
    "low_cable",
    "shoulder_flexion",
    "Face away from the low pulley and raise the handle in front to about shoulder height without leaning back.",
    [primary("shoulders"), secondary("core", 0.15)],
    { sideMode: "per_side" },
  ),
  exercise(
    "High-to-low cable wood chop",
    "high_cable",
    "rotation",
    "Use a single handle from the high pulley. Brace the trunk and pull diagonally across the body while rotating through the upper torso and hips together.",
    [primary("core"), secondary("shoulders", 0.2)],
    { sideMode: "per_side" },
  ),
  exercise(
    "Machine leg extension",
    "multi_gym",
    "knee_extension",
    "Line the machine pivot up with your knee and place the lower pad above the ankle. Extend smoothly without lifting off the seat.",
    [primary("quads")],
  ),
  exercise(
    "Standing cable leg curl",
    "low_cable_ankle_strap",
    "knee_flexion",
    "Attach the ankle strap to the low pulley. Hold the frame for balance and curl the heel toward the glute without moving the thigh forward.",
    [primary("hamstrings")],
    { sideMode: "per_leg" },
  ),
  exercise(
    "Cable glute kickback",
    "low_cable_ankle_strap",
    "hip_extension",
    "Attach the ankle strap to the low pulley. Brace against the frame and extend the leg behind you without arching the lower back.",
    [primary("glutes"), secondary("hamstrings", 0.3)],
    { sideMode: "per_leg" },
  ),
  exercise(
    "Standing cable hip abduction",
    "low_cable_ankle_strap",
    "hip_abduction",
    "Attach the ankle strap and stand side-on to the low pulley. Move the outside leg away from the body while keeping the pelvis level.",
    [primary("glutes")],
    { sideMode: "per_leg" },
  ),

  exercise(
    "Flat dumbbell bench press",
    "dumbbell_and_bench",
    "horizontal_push",
    "Set the bench flat. Keep feet planted and shoulder blades set, lower the dumbbells beside the chest, and press over the shoulders.",
    [primary("chest"), secondary("triceps", 0.55), secondary("shoulders", 0.35)],
  ),
  exercise(
    "Dumbbell chest fly",
    "dumbbell_and_bench",
    "horizontal_push",
    "Lie on the bench with a soft elbow bend. Open the arms only as far as the shoulders stay comfortable, then bring the dumbbells back over the chest.",
    [primary("chest"), secondary("shoulders", 0.25)],
  ),
  exercise(
    "Dumbbell pullover",
    "dumbbell_and_bench",
    "shoulder_extension",
    "Lie lengthwise on the bench and hold one dumbbell over the chest. Lower it behind the head with ribs controlled, then pull it back over the chest.",
    [primary("chest"), secondary("back", 0.4), secondary("triceps", 0.4)],
  ),
  exercise(
    "Seated dumbbell shoulder press",
    "dumbbell_and_bench",
    "vertical_push",
    "Set the bench upright. Keep your back supported, start the dumbbells near shoulder height, and press without over-arching.",
    [primary("shoulders"), secondary("triceps", 0.55)],
  ),
  exercise(
    "Arnold press",
    "dumbbell_and_bench",
    "vertical_push",
    "Sit against the upright bench. Start with palms facing you, rotate as you press, and reverse the motion under control.",
    [primary("shoulders"), secondary("triceps", 0.4)],
  ),
  exercise(
    "Bent-over dumbbell reverse fly",
    "dumbbell",
    "horizontal_pull",
    "Hinge with a neutral spine and a soft elbow bend. Raise the dumbbells out to the sides without shrugging.",
    [primary("shoulders"), secondary("back", 0.55)],
  ),
  exercise(
    "Dumbbell hammer curl",
    "dumbbell",
    "elbow_flexion",
    "Keep palms facing each other and upper arms close to the torso. Curl without swinging and lower fully under control.",
    [primary("biceps"), secondary("grip", 0.3)],
  ),
  exercise(
    "Incline dumbbell curl",
    "dumbbell_and_bench",
    "elbow_flexion",
    "Recline the bench and let the arms hang beneath the shoulders. Curl without bringing the elbows forward.",
    [primary("biceps")],
  ),
  exercise(
    "Dumbbell skull crusher",
    "dumbbell_and_bench",
    "elbow_extension",
    "Lie on the bench with dumbbells over the shoulders. Bend only at the elbows, lower beside the head, then extend without flaring excessively.",
    [primary("triceps")],
  ),
  exercise(
    "Seated dumbbell overhead triceps extension",
    "dumbbell_and_bench",
    "elbow_extension",
    "Sit against the upright bench and hold one dumbbell overhead. Keep the elbows pointing forward as you lower behind the head and extend.",
    [primary("triceps")],
  ),
  exercise(
    "Goblet squat",
    "dumbbell_or_kettlebell",
    "squat",
    "Hold one dumbbell or kettlebell at the chest. Sit between the hips, keep the whole foot planted, and stand without the knees collapsing inward.",
    [primary("quads"), secondary("glutes", 0.75), secondary("core", 0.3)],
  ),
  exercise(
    "Dumbbell reverse lunge",
    "dumbbell",
    "lunge",
    "Hold dumbbells at your sides and step back far enough for both knees to bend comfortably. Drive through the front foot to return.",
    [primary("glutes"), secondary("quads", 0.8), secondary("hamstrings", 0.3)],
    { sideMode: "per_leg" },
  ),
  exercise(
    "Dumbbell hip thrust",
    "dumbbell_and_bench",
    "hip_extension",
    "Place the upper back against the bench and a padded dumbbell across the hips. Drive the hips up while keeping the ribs down.",
    [primary("glutes"), secondary("hamstrings", 0.4), secondary("core", 0.2)],
  ),
  exercise(
    "Standing dumbbell calf raise",
    "dumbbell",
    "plantar_flexion",
    "Hold dumbbells at your sides, rise onto the balls of the feet, pause at the top, and lower through a comfortable range.",
    [primary("calves")],
  ),
  exercise(
    "Dumbbell farmer carry",
    "dumbbell",
    "carry",
    "Hold a dumbbell in each hand, stand tall, and walk or march in place without leaning. Record the working time.",
    [primary("grip"), secondary("core", 0.7), secondary("back", 0.45)],
    { trackingType: "duration" },
  ),
  exercise(
    "Dumbbell suitcase carry",
    "dumbbell",
    "carry",
    "Hold one dumbbell at your side and walk or march in place while keeping the torso upright. Record equal time on each side.",
    [primary("core"), secondary("grip", 0.8), secondary("back", 0.3)],
    { trackingType: "duration", sideMode: "per_side" },
  ),
  exercise(
    "Dumbbell shrug",
    "dumbbell",
    "scapular_elevation",
    "Hold dumbbells at your sides and raise the shoulders straight up. Pause briefly and lower without rolling the shoulders.",
    [primary("back"), secondary("grip", 0.4)],
  ),

  exercise(
    "Kettlebell deadlift",
    "kettlebell",
    "hinge",
    "Stand over the kettlebell, push the hips back, brace, and stand by driving through the floor. Return it between the feet with the same hinge.",
    [primary("glutes"), secondary("hamstrings", 0.8), secondary("quads", 0.45), secondary("back", 0.25), secondary("grip", 0.3)],
  ),
  exercise(
    "Single-arm kettlebell clean",
    "kettlebell",
    "hinge",
    "Drive the bell from the hinge into the rack position and guide it around the forearm rather than letting it crash. Practice each side separately.",
    [primary("glutes"), secondary("hamstrings", 0.5), secondary("shoulders", 0.4), secondary("grip", 0.4), secondary("quads", 0.35), secondary("core", 0.3)],
    { sideMode: "per_side" },
  ),
  exercise(
    "Single-arm kettlebell strict press",
    "kettlebell",
    "vertical_push",
    "Start from a stable rack position, brace the trunk, and press overhead without using leg drive or leaning sideways.",
    [primary("shoulders"), secondary("triceps", 0.55), secondary("core", 0.35)],
    { sideMode: "per_side" },
  ),
  exercise(
    "Kettlebell Turkish get-up",
    "kettlebell",
    "ground_to_stand",
    "Use a light bell and move through each position slowly while keeping the loaded arm vertical. Reverse the sequence to return to the floor.",
    [primary("core"), secondary("shoulders", 0.65), secondary("glutes", 0.4), secondary("quads", 0.35), secondary("grip", 0.25)],
    { sideMode: "per_side" },
  ),
  exercise(
    "Kettlebell halo",
    "kettlebell",
    "shoulder_circulation",
    "Hold the kettlebell by the horns and circle it slowly around the head while keeping the ribs down. Alternate directions.",
    [primary("shoulders"), secondary("core", 0.35)],
  ),
  exercise(
    "Kettlebell front-rack reverse lunge",
    "kettlebell",
    "lunge",
    "Hold the kettlebell in the rack position, step the opposite leg back, and keep the torso stacked as you return through the front foot.",
    [primary("glutes"), secondary("quads", 0.8), secondary("core", 0.4), secondary("hamstrings", 0.3)],
    { sideMode: "per_leg" },
  ),

  exercise(
    "EZ-bar biceps curl",
    "ez_bar",
    "elbow_flexion",
    "Use a comfortable angled grip. Keep the upper arms still, curl without leaning back, and lower to full elbow extension.",
    [primary("biceps"), secondary("grip", 0.2)],
  ),
  exercise(
    "EZ-bar reverse curl",
    "ez_bar",
    "elbow_flexion",
    "Take an overhand angled grip and keep the wrists neutral. Curl with the elbows close to the torso and control the lowering phase.",
    [primary("biceps", 0.75), secondary("grip", 0.55)],
  ),
  exercise(
    "EZ-bar skull crusher",
    "ez_bar_and_bench",
    "elbow_extension",
    "Lie on the bench with the bar over the shoulders. Bend at the elbows to lower toward the forehead or just behind the head, then extend under control.",
    [primary("triceps")],
  ),
  exercise(
    "EZ-bar close-grip floor press",
    "ez_bar",
    "horizontal_push",
    "Lie on the floor with a shoulder-width grip. Lower until the upper arms touch down softly, pause, and press without letting the elbows flare wide.",
    [primary("triceps"), secondary("chest", 0.7), secondary("shoulders", 0.3)],
  ),
  exercise(
    "EZ-bar bent-over row",
    "ez_bar",
    "horizontal_pull",
    "Hinge with a neutral spine, brace, and row the bar toward the lower ribs without jerking the torso upward.",
    [primary("back"), secondary("biceps", 0.45), secondary("grip", 0.25)],
  ),

  exercise(
    "Resistance-band pull-apart",
    "resistance_band",
    "horizontal_pull",
    "Hold the band at shoulder height with straight arms. Pull it apart by moving the shoulder blades back and keep the ribs down.",
    [primary("shoulders"), secondary("back", 0.6)],
  ),
  exercise(
    "Resistance-band face pull",
    "resistance_band",
    "horizontal_pull",
    "Anchor the band above eye level. Pull toward the face with elbows high and rotate the hands apart at the finish.",
    [primary("shoulders"), secondary("back", 0.6), secondary("biceps", 0.2)],
  ),
  exercise(
    "Resistance-band external rotation",
    "resistance_band",
    "shoulder_rotation",
    "Anchor the band around elbow height. Keep the elbow against your side and rotate the forearm outward without turning the torso.",
    [primary("shoulders")],
    { sideMode: "per_side" },
  ),
  exercise(
    "Resistance-band Pallof press",
    "resistance_band",
    "anti_rotation",
    "Anchor the band around chest height. Stand side-on, press the hands away from the chest, and resist being pulled into rotation.",
    [primary("core"), secondary("shoulders", 0.15)],
    { sideMode: "per_side" },
  ),
  exercise(
    "Resistance-band lateral walk",
    "resistance_band",
    "hip_abduction",
    "Place the loop band above the knees or around the ankles. Keep tension as you take controlled side steps without letting the knees collapse inward.",
    [primary("glutes"), secondary("quads", 0.25)],
  ),

  exercise(
    "Push-up",
    "bodyweight",
    "horizontal_push",
    "Keep the body in a straight line, lower the chest between the hands, and press the floor away without letting the hips sag.",
    [primary("chest"), secondary("triceps", 0.6), secondary("shoulders", 0.4), secondary("core", 0.25)],
    { defaultLoadType: "bodyweight" },
  ),
  exercise(
    "Feet-elevated push-up",
    "bench_and_bodyweight",
    "horizontal_push",
    "Place the feet securely on the bench and hands on the floor. Keep the body rigid and lower under control before pressing back up.",
    [primary("chest"), secondary("shoulders", 0.65), secondary("triceps", 0.55), secondary("core", 0.3)],
    { defaultLoadType: "bodyweight" },
  ),
];
